<a href="https://colab.research.google.com/github/ced-sys/SubTerra/blob/main/Kenya_HFC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point

In [8]:
df=pd.read_excel('/content/IHFC_2024_GHFDB.xlsx', sheet_name='data release2024')
print(df.columns)

/usr/local/lib/python3.11/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

Index(['P1', 'P2', 'P3', 'P4', 'P5', 'P6', 'P7', 'P8', 'P9', 'P10', 'P11',
       'P12', 'P13', 'C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8', 'C9',
       'C10', 'C11', 'C12', 'C13', 'C14', 'C15', 'C16', 'C17', 'C18', 'C19',
       'C20', 'C21', 'C22', 'C23', 'C24', 'C25', 'C26', 'C27', 'C28', 'C29',
       'C30', 'C31', 'C32', 'C33', 'C34', 'C35', 'C36', 'C37', 'C38', 'C39',
       'C40', 'C41', 'C42', 'C43', 'C44', 'C45', 'C46', 'C47', 'C48', 'C49',
       'Unnamed: 62', 'Unnamed: 63', 'Unnamed: 64', 'Unnamed: 65',
       'Unnamed: 66', 'Unnamed: 67', 'Unnamed: 68', 'Unnamed: 69',
       'Unnamed: 70', 'Unnamed: 71', 'Unnamed: 72', 'Unnamed: 73'],
      dtype='object')

In [9]:
df['P1']=pd.to_numeric(df['P1'], errors='coerce')
df['P5']=pd.to_numeric(df['P5'], errors='coerce')
df['P4']=pd.to_numeric(df['P4'], errors='coerce')

df.dropna(subset=['P1', 'P5', 'P4'])

,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10,...,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71,Unnamed: 72,Unnamed: 73
5,366.0,NaN,44593,49.615000,-129.981000,-2383.7,[offshore (continental)],NaN,NaN,NaN,...,NaN,open to review,NaN,North Pacific Ocean,Juan de Fuca Plate,marine,2008,Ux.Mx.-------,R24-P000001,R24-000001
6,62.0,NaN,?,43.046700,-30.063300,-2248.1,[offshore (marine)],NaN,NaN,NaN,...,NaN,open to review,NaN,North Atlantic Ocean,North American Plate,marine,2008,Ux.Mx.-------,R24-P000002,R24-000002
7,41.0,NaN,?,43.031700,-30.000000,-2054.1,[offshore (marine)],NaN,NaN,NaN,...,NaN,open to review,NaN,North Atlantic Ocean,North American Plate,marine,2008,Ux.Mx.-------,R24-P000003,R24-000003
8,23.0,NaN,?,43.048300,-29.086700,-1805.4,[offshore (marine)],NaN,NaN,NaN,...,NaN,open to review,NaN,North Atlantic Ocean,North American Plate,marine,2008,Ux.Mx.-------,R24-P000004,R24-000004
9,191.0,NaN,?,43.028300,-29.081700,-1572.5,[offshore (marine)],NaN,NaN,NaN,...,NaN,open to review,NaN,North Atlantic Ocean,North American Plate,marine,2008,Ux.Mx.-------,R24-P000005,R24-000005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91182,69.8,10.8,X5,41.642778,106.584167,NaN,[onshore (continental)],Average HF,[unspecified],2242,...,2023-11,completed,China,NaN,Asia,continental,2020,Ux.M3.-------,R24-P071932,R24-091178
91183,66.5,6.7,Y5,41.590833,106.475556,NaN,[onshore (continental)],Average HF,[unspecified],2899,...,2023-11,completed,China,NaN,Asia,continental,2020,Ux.M3.-------,R24-P071933,R24-091179
91184,66.5,6.7,Y5,41.590833,106.475556,NaN,[onshore (continental)],Average HF,[unspecified],2899,...,2023-11,completed,China,NaN,Asia,continental,2020,Ux.M3.-------,R24-P071933,R24-091180
91185,68.1,4.9,Y7,41.712500,106.541389,NaN,[onshore (continental)],Average HF,[unspecified],2184,...,2023-11,completed,China,NaN,Asia,continental,2020,Ux.M3.-------,R24-P071934,R24-091181
91186,68.1,4.9,Y7,41.712500,106.541389,NaN,[onshore (continental)],Average HF,[unspecified],2184,...,2023-11,completed,China,NaN,Asia,continental,2020,Ux.M3.-------,R24-P071934,R24-091182

In [10]:
gdf=gpd.GeoDataFrame(
    df,
    geometry=gpd.points_from_xy(df['P4'], df['P5']),
    crs='EPSG:4326'
)

In [12]:
import os
os.environ['SHAPE_RESTORE_SHX']='YES'
kenya=gpd.read_file('/content/gadm41_KEN_0.shp')

In [13]:
gdf_kenya=gdf[gdf.geometry.within(kenya.unary_union)]

<ipython-input-13-784ad4a48661>:1: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  gdf_kenya=gdf[gdf.geometry.within(kenya.unary_union)]

In [14]:
gdf_kenya.to_file('heat_flow_kenya.geojson', driver='GeoJSON')
gdf_kenya[['P1', 'P4', 'P5']].to_csv('heat_flow_kenya.csv', index=False)

In [15]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [16]:
import shutil

shutil.copy('heat_flow_kenya.csv', '/content/drive/MyDrive/SubTerra/heat_flow_kenya.csv')
shutil.copy('heat_flow_kenya.geojson', '/content/drive/MyDrive/SubTerra/heat_flow_kenya.geojson')

'/content/drive/MyDrive/SubTerra/heat_flow_kenya.geojson'